spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tangerine_prototype
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  profiles:
    include: secret, region
  sql:
    init:
      mode: always