name: CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
    # Install Java 17
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Spring Boot Build
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.6.0
      with:
        arguments: build

    # Build Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY_NAME }} .

    # Login DockerHub
    - name: Login DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Push image to DockerHub
    - name: Push image to DockerHub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY_NAME }}

    # Deploy on Qnap NAS
    - name: Deploy on Qnap Nas
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NAS_HOST }}
        username: ${{ secrets.NAS_USERNAME }}
        password: ${{ secrets.NAS_PASSWORD }}
        script: |
            /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY_NAME }}:latest
            /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker stop ${{ secrets.DOCKERHUB_REPOSITORY_NAME }} || true
            /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker rm ${{ secrets.DOCKERHUB_REPOSITORY_NAME }} || true
            /share/CACHEDEV1_DATA/.qpkg/container-station/bin/docker run -d \
            --name ${{ secrets.DOCKERHUB_REPOSITORY_NAME }} \
              -v /share/Container/app:/config \
              -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
              ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY_NAME }}:latest \
